language: ruby

install:
  # Install Jekyll and dependencies
  - bundle install

branches:
  only:
    - source

script: bundle exec rake site:deploy --quiet
env:
  global:
     secure: "B+0E/niTxid8tLw1XL96KWexBW7oO3G8OxjxMcSOjP8d36PPZmYWHfHLupqMjP/qs9NjrbD2mf9080N5p85woXiM91WZ6iSKaqJmEAMfshLZaDRJHWfXtevKA8JfgkDgvMBuCtpuYob2Qcqh7aje0FXZ63ICJ2XJ/BhQkriDMsY="
