language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1.0
bundler_args: --without development --deployment --jobs=3 --retry=3
script: 
  - ./_scripts/add-filenames-to-posts.sh
  - bundle exec rake site:deploy --quiet
branches:
  only:
  - source