language: ruby
script: ./build.sh
branches:
  only:
  - source
install:
- bundle install
rvm:
- 2.1.2
env:
  global:
    secure: ZaPtQK27rzT2iHWsuOBptE6G3+1AgwyiOirztpWCOI5/uxwWeKM1eIr1XODWtLJUUwT/LOinKjxvmOFgTyXJjsYnirn6ZrGnY0aSYbeFB8/BxO6iL1+6WoIIiHgVPMXW3oNW8FIbr735LTlWXBOyquWtVKdLcjP4s4+mVxXkKzA=
