language: ruby
cache: bundler
sudo: false
# install:
# - bundle install --without development --deployment --jobs=3 --retry=3
bundler_args: --without development --deployment --jobs=3 --retry=3
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - source