language: ruby

install:
  # Install Jekyll and dependencies
  - bundle install

branches:
  only:
    - source

script: bundle exec rake site:deploy --quiet
env:
  global:
     secure: "CKEirm3sdWZAVE0LvIX0Ltf4k7bnc0/Fyi0cMLVllcuCUCbdd6bD8KsmUO4WsoGZBuBJYReN2tx5r9ijdjoU75Dgoi47R2npWQWRIZVoZmHNYwtHolKGrzWGWbst5VfTs7/DXDRCHnuYxRIbG77FpIPfH/iC9agNsb9FJZvhjK4="
