# Site wide configuration

title:            Just another tech blog
locale:           en_US

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.

production_url:  http://test.clburlison.com
source_url:      http://github.com/clburlison/blog


# Jekyll configuration

permalink: /blog/:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Clayton Burlison
  avatar: me.jpg
  bio: "A Mac sysadmin, documenting useful code, ideas, & guides."
  email: clburlison@gmail.com
  disqus-shortname: clburlison
  twitter: clburlison
  facebook: clburlison
  google:
    plus: 
    analytics: UA-49614309-2
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: clburlison
  stackoverflow:
  linkedin: clburlison
  instagram: 
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam: DancingMonkey
  dribbble:


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "CNAME"]
