# Site wide configuration

title:            Just another tech blog
locale:           en_US
url:  https://clburlison.com

# Travis.ci info
username: clburlison
repo: clburlison.github.io
branch: source
relative_source: ../clburlison.github.io/
destination: ../clburlison.github.io-master/

# Jekyll configuration

permalink: /blog/:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

category_dir: blog/categories

# Site owner
owner:
  name: Clayton Burlison
  avatar: me.jpg
  bio: "A Mac sysadmin, documenting useful code, ideas, & guides."
  email: clburlison@gmail.com
  disqus-shortname: clburlison
  twitter: clburlison
  facebook:
  google:
    plus: 
    analytics:
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: clburlison
  stackoverflow:
  linkedin: clburlison
  instagram: 
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam: 
  dribbble:


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", ".travis.yml", "vendor"]

# Settings for sitemap_generator plugin.
sitemap:
    exclude:
        - "/feed.xml"
        - "/blog/archives"
        - "/blog/categories"
    include_posts:
        - "/index.html"
        - "/blog/index.html"
        - "/blog/"


# Setting for prose.io
prose:
  ignore:	
    - /_data
    - /_includes
    - /_layouts
    - /_plugins
    - /_posts_sample
    - /_sass
    - /_templates
    - /archives
    - /categories
    - /assets	
    - 404.md
    - _octopress.yml	
    - _config.yml
    - _config-dev.yml    	
    - index.html
    - CNAME
    - feed.xml
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - Rakefile
    - README.md
    - robots.txt
    - .gitignore
    - .nojekyll
    - .travis.yml
    - favicon.ico
    - favicon.png
    - license.txt
    - index.md
        
  siteurl: "https://clburlison.com"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "date"
          value: ""
          type: "text"
          alterable: true
      - name: "modified"
        field:
          element: "text"
          label: "modified"
          value: ""
          type: "text"
          alterable: true 
      - name: "comments"
        field:
          element: checkbox
          label: "Comments"
          value: "true"
          alterable: true         
      - name: "categories"
        field:
          element: "multiselect"
          label: "categories"
          help: "Enter one or more tags to categorize your post, E.g., bash, munki, personal."
          alterable: true