# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Just another tech blog"
title_separator          : "-"
name                     : "Clayton Burlison"
description              : "A Mac sysadmin, documenting useful code, ideas, & guides."
url                      : "https://clburlison.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
gh_repo                  :
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "facebook", "google-plus", custom"
  disqus:
    shortname            : "clburlison" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : "clburlison"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "site_logo.jpg" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/clburlison"
    - "https://github.com/clburlison"

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-49614309-2"

# Google AdSense
google_ad_client         :
google_ad_slot           :


# Site Author
author:
  name             : "Clayton Burlison"
  avatar           : "me.jpg"
  bio              : "A Mac sysadmin, documenting useful code, ideas, & guides."
  location         : "Fort Worth, Texas"
  email            : "clburlison@gmail.com"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           : "clburlison"
  facebook         : "clburlison"
  foursquare       :
  github           : "clburlison"
  google_plus      :
  keybase          :
  instagram        : "clburlison"
  lastfm           :
  linkedin         : "clburlison"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "clburlison"
  vine             :
  weibo            :
  xing             :
  youtube          : "clburlison"


# site yaml defaults
defaults:
  # _pages/about
  - scope:
      path: "_pages/about"
      type: pages
    values:
      layout: single
      read_time: false
      comments: false
      share: false
      related: false
      author_profile: false
      sidebar:
        nav: "about"
      header:
        image: /unsplash/photo-1446426156356-92b664d86b77.jpeg
        caption: "Photo credit: [**Unsplash**](https://unsplash.com/photos/RdyMe8KQAV0)"
  # _pages/archives
  - scope:
      path: "_pages/archives"
      type: pages
    values:
      layout: archive
      read_time: false
      comments: false
      share: false
      related: false
      author_profile: false
      sidebar:
        nav: "archive"
      header:
        image: /unsplash/photo-1457685373807-8c4d8be4c560.jpeg
        caption: "Photo credit: [**Unsplash**](https://unsplash.com/photos/90FzfXFEEjo)"
  # _drafts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      related: false
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: false
      author_profile: true


# Collections
# collections:
#   guides:
#     output: true
#     permalink: /:collection/:path/

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
  - jekyll-archives


# Archives
categories:
  type: jekyll-archives
  path: /categories/
tags:
  type: jekyll-archives
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Travis.ci info
username: clburlison
repo: clburlison.github.io
branch: source
relative_source: ../clburlison.github.io/
destination: ../clburlison.github.io-master/
# pullrequesturl : "http://prose.io/#clburlison/clburlison.github.io/edit/source/_posts/"
github_repo_url: https://github.com/clburlison/clburlison.github.io/


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - vendor
  - helper.sh
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Setting for prose.io
prose:
  ignore:	
    - /_data
    - /_includes
    - /_layouts
    - /_plugins
    - /_posts_sample
    - /_sass
    - /_templates
    - /archives
    - /categories
    - /assets	
    - 404.md
    - _octopress.yml
    - _config.yml    
    - _config-dev.yml
    - CNAME
    - feed.xml
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - Rakefile
    - README.md
    - robots.txt
    - .gitignore
    - .nojekyll
    - .travis.yml
    - favicon.ico
    - favicon.png
    - license.txt
        
  siteurl: "https://clburlison.com"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "modified"
        field:
          element: "text"
          label: "modified"
      - name: "excerpt"
        field:
          element: "text"
          label: "excerpt"
      - name: "comments"
        field:
          element: checkbox
          value: "true"
          label: "Comments"
          alterable: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          help: "Enter one or more tags to categorize your post, E.g., bash, munki, personal."
          alterable: true
    _drafts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "modified"
        field:
          element: "text"
          label: "modified"
      - name: "excerpt"
        field:
          element: "text"
          label: "excerpt"
      - name: "comments"
        field:
          element: checkbox
          value: "true"
          label: "Comments"
          alterable: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          help: "Enter one or more tags to categorize your post, E.g., bash, munki, personal."
          alterable: true