defaults: &defaults
  working_directory: /tmp/clburlison.com
  environment:
    - SOURCE_DIR: /tmp/clburlison.com/public
    - S3_BUCKET: s3://clburlison.com


version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: jguyomard/hugo-builder:0.31
    steps:
      - checkout
      - run:
          name: Download submodules for our theme
          command: git submodule sync && git submodule update --init
      - run:
          name: Compile site
          command: /usr/local/bin/hugo --destination "$SOURCE_DIR"
      - persist_to_workspace:
          root: /tmp/clburlison.com
          paths:
            - public

  upload:
    <<: *defaults
    docker:
      - image: xueshanf/awscli
    steps:
      - attach_workspace:
          at: /tmp/clburlison.com
      - run:
          name: Upload to s3
          command: aws s3 sync "$SOURCE_DIR" "$S3_BUCKET" --delete


workflows:
  version: 2
  build-and-upload:
    jobs:
      - build
      - upload:
          requires:
            - build